### ISSUE TITLE
Hide some variables which shouldn't be editable

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUIDesigner#14]
I think we talked briefly about this feature.

The server can send some groups of variables which shouldn't be editable e.g. V2 variables.

**Comment by maximilianweidenauer** [comment]
Visible/Invisible is being handled on the client.

When transferType is partial, should the editors for full transferType be invisible to not confuse the user, if they don't know about full mode? @rjahn

**Comment by rjahn** [comment]
I don't know the use-case anymore.

Why is there a difference between partial and full?

**Comment by maximilianweidenauer** [comment]
There is not really a difference between partial and full, but eg. if the mode is partial and a user doesn't know what the full variables mean, they could get confused.

**Comment by rjahn** [comment]
OK, so this is a client decission.
