### ISSUE TITLE
Color not set

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUIDesigner#20]
Open the color chooser and set e.g. red. Open it again and change the slider. The color is changed in chooser, but if you close the chooser, nothing is changed.

It's not clear how to use the color... There's not "ok" button....

**Comment by maximilianweidenauer** [comment]
Do you remember at which color chooser this was happening? It could be that there is still no subscriber for this specific variable and thats why the color didn't update...
E.g. the button color does update when you change the color in the color chooser

**Comment by rjahn** [comment]
It made no difference for me - every color.

**Comment by maximilianweidenauer** [comment]
Changing colors works for me, now we even have the new color picker can I close this or do you want to check this out again when you have the time?

**Comment by rjahn** [comment]
Will check in future, close this issue. Will open a new one if necessary.
