### ISSUE TITLE
Changing standard style didn't work

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUIDesigner#21]
basti is the standard style

If you change the style and press upload, nothing is changed after reload browser.

**Comment by maximilianweidenauer** [comment]
I've just tried this after building and using the designer in visionx (not live version). I've reloaded after uploading and you're right the style didn't change, after clearing cache the changes are applied, so I'll check if I can trigger a cache clear or we will have to tell the user to clear their cache themselves

**Comment by rjahn** [comment]
or simply add a ?version=uuid to the URL
In this case, the browser uses the new version

**Comment by maximilianweidenauer** [comment]
Right, the server does this already for the application.css file, maybe we can use this for theme and scheme also? When server receives upload send new version via websocket? Or should I do this on my own on the client

**Comment by maximilianweidenauer** [comment]
I'm just going to do it on the client.

**Comment by rjahn** [comment]
The server can't do anything if the client doesn't send a request, so it's necessary to change the access URL, in the html page.
