### ISSUE TITLE
Default style names and scheme names

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUIDesigner#23]
Currently, there are 2 textfields, but you have to know which styles and color schemes exist. It would be better to have comboboxes and a + (-> new) button. So, choose an existing combination or create a new combination...

A popup should appear. It should be possible to create a new style based on an existing style/scheme, but with a new name....

**Comment by maximilianweidenauer** [comment]
Yes I could do it similar to the PrimeReact-Editor. There you choose at the very beginning which theme you want to overwrite. https://www.primefaces.org/designer-react/#/

I had planned to introduce a screen like this, for the express mode https://github.com/sibvisions/reactUIDesigner/issues/15

**Comment by maximilianweidenauer** [comment]
This is now possible via express mode. You can load the existing schemes/themes via a combobox and can either change them or use them as a base to create a new scheme/theme
