### ISSUE TITLE
odd/even styling in table

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUIDesigner#25]
didn't work to change the colors of odd/even rows

**Comment by maximilianweidenauer** [comment]
It works for me...

![image](https://user-images.githubusercontent.com/66732863/201864619-82062d1a-777b-4964-99c4-ced2645acb56.png)

**Comment by maximilianweidenauer** [comment]
Had issues with uploading, reloading when testing this. So https://github.com/sibvisions/reactUIDesigner/issues/21 this issue wasn't actually fixed, now it is and this works too!
