### ISSUE TITLE
Login styling

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUIDesigner#28]
Mask Background

-> Fields background

Default looks black, but color is gray?

Order:

Logo background
Fields background

Top Bottom Padding -> also changes the padding under the logo, not only top and bottom of the window.

**Comment by rjahn** [comment]
In Standard-Topbar categorie is a property: Background and Logo Background.

We could use Background and Logo Background in Login category as well instead of Mask Background.

It's alwas better to have the same labels where possible.

**Comment by maximilianweidenauer** [comment]
With the new color-picker default not black anymore --> #33, changed the order and labels. also top bottom padding doesn't change padding under logo anymore
