### ISSUE TITLE
Labels and Properties

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUIDesigner#30]
What is the Standard-Topbar? Do we have a Topbar? If not, simply use Topbar
We have a Full-Topbar... but the difference is unclear 

There's no order for the categories.

Error-Bar -> Error Bar

SysColors -> System Colors

CrashView -> Crash View

CellPadding -> Cell Padding -> which cells do you mean?

**Comment by maximilianweidenauer** [comment]
Standard-Topbar -> Standard-Menu
Corporation-Topbar -> Corporation-Menu
Full-Topbar -> transferType Full (V2) Menu

If I all call them "Topbar" they will overwrite thmeselves in the map, but I can restructure the map so that I can change the display-name

**Comment by rjahn** [comment]
What about: Topbar (Standard), Topbar (Corporation), Topbar (Full)

I don't like the Topbar-Standard (the minus sign without spaces)

**Comment by maximilianweidenauer** [comment]
This is also good, but I'm still going to change the map so a proper display-name can be shown. https://github.com/sibvisions/reactUIDesigner/issues/32 in this ticket I also want to hide editors so a visible-flag is also necessary, so I need to rebuild the map anyways

**Comment by maximilianweidenauer** [comment]
map with display names was introduced, now all topbars are only called "topbar". Also I've changed the labels which you pointed out.
