### ISSUE TITLE
Font size 20 in Login

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUIDesigner#31]
Set the general font size to 20

The login view has problems with this size: wrong left padding?

<img width="454" alt="image" src="https://user-images.githubusercontent.com/1307043/203662043-d3ea12fa-b4ed-4b21-92ec-ffde53b8c73a.png">

**Comment by rjahn** [comment]
If I try to set the Button background -> nothing happens?

Is the Button category the wrong category for the Login button?

**Comment by maximilianweidenauer** [comment]
Fixed button not setting background in multiple components (errordialog and the mfa's) and the padding issue
