### ISSUE TITLE
Table row height: 2

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUIDesigner#34]
If you set the table row height to 2 -> nothing will happen?

**Comment by maximilianweidenauer** [comment]
I've just checked this out and it seems like 16px is the minimum height for the table. I'll add this information to the tooltip, should a lower number still be enterable or should I change it to 16px whenever someone tries to enter a lower value?

**Comment by maximilianweidenauer** [comment]
Back then nothing happened, because I hadn't implemented the part where the components would update, now the components do update but as I said, it doesn't get lower than 16px

**Comment by rjahn** [comment]
simply set it to 16 if it's lower...
