### ISSUE TITLE
Images - Disk Button

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUIDesigner#37]
Please use a different icon. Looks like a Save Button. The disk icon is better for saving.

**Comment by maximilianweidenauer** [comment]
https://github.com/sibvisions/reactUIDesigner/issues/19 ???

**Comment by rjahn** [comment]
Nope, the Images have a small button with a disk in it. The disk means for me: save
But if you press the button, a file chooser is shown. So, the icon should be changed to a "load" icon.

**Comment by maximilianweidenauer** [comment]
Ah okay, I was thinking about the upload when uploading the entire scheme/theme

**Comment by maximilianweidenauer** [comment]
Now using File-Upload icon, is that ok?
![image](https://user-images.githubusercontent.com/66732863/203965472-074a6adc-4161-4f41-85f8-a82abb1cc0e0.png)
