### ISSUE TITLE
Design Button position

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUIDesigner#42]
If designer is enabled -> remove the button from right/bottom and add it to the designer bar? before reload? or centered (white background) ???

**Comment by maximilianweidenauer** [comment]
![image](https://user-images.githubusercontent.com/66732863/206677445-11632b46-45d3-4c00-8be5-de5798743209.png)

![image](https://user-images.githubusercontent.com/66732863/206677967-2f032745-62b7-4a29-a7ec-b3d113286725.png)

I prefer the one where the button is on the left

**Comment by rjahn** [comment]
the one where the button is left
