### ISSUE TITLE
Use newly created scheme or theme if it has a different name

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUIDesigner#43]
When a user is initially opening the designer with eg. "default" and "basti". Then they change the scheme and theme and uses a different name. Then they upload it to the server. Obviously they would want to use it on reload again but in VisionX the setting will still be set to "default" and "basti". So eventually the user will have to change it in the VisionX settings.

But shortly after the upload I can maybe try to edit the URL parameters to add the correct theme/scheme to load.

**Comment by rjahn** [comment]
URL parameters or keep the last saved name in local storage?
