### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUIDesigner#47]
Either the translation file needs to be extended or an extra translation file is needed for the designer, I will simply pass it from the reactui to the designer so the designer can use it.

**Comment by rjahn** [comment]
list of texts?

Maybe we will introduce a new translation file, but currently not planned.

**Comment by maximilianweidenauer** [comment]
I'll provide a list of texts.

**Comment by rjahn** [comment]
If it's easy to use a different file, do following:

Search a file by name: translation_cssdesigner_<lang>.xml

To test: Simply create such file in the same place as translation_<lang>.xml
You should automatically receive the file!

**Comment by rjahn** [comment]
Where's the translation file?

**Comment by maximilianweidenauer** [comment]
[translation_cssdesigner.zip](https://github.com/sibvisions/reactUIDesigner/files/14509459/translation_cssdesigner.zip)
zip cause github doesnt support xml

**Comment by maximilianweidenauer** [comment]
[translation_cssdesigner.zip](https://github.com/sibvisions/reactUIDesigner/files/14509464/translation_cssdesigner.zip)
ZIP because GitHub doesn't support xml (now correct file)
