### ISSUE TITLE
Custom images override default images

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUIDesigner#48]
If you set a custom image for new theme A, it will override default images... but if you create a new theme B with another image, it will override the image of theme A...

We need theme dependent images.

**Comment by maximilianweidenauer** [comment]
Currently in the public folder we have the assets folder which contains these files:

```
public
|-- assets
     |-- logo_big.png
     |-- logo_login.png
     |-- logo_small.png
```

when uploading the files to the server, those files will get updated.
Now to get theme dependent images, we would have to add a directory for each theme which would contain the images. Eg:
```
public
|-- assets
    |-- basti
        |-- logo_big.png
        |-- logo_login.png
        |-- logo_small.png
```

So when uploading, the server needs to put the image files in the correct directory

**Comment by maximilianweidenauer** [comment]
When a new theme is created, the image-directory needs to be created with the images which are currently selected in the designer!

**Comment by maximilianweidenauer** [comment]
I have already changed the project structure. The last part of this ticket is depending on the server implementation and how I have to upload the images!

**Comment by rjahn** [comment]
Nothing to do, only check that you send the theme-file-name property always!

With this property, the server is able to know the right theme name and is able to put the images in the right location!

**Comment by maximilianweidenauer** [comment]
Ich tried that and it did not work.
I've tried the theme-file-name property with: `basti.css` and `basti`

the image is still just being saved in `ui/assets/logo_big.png`
![image](https://github.com/sibvisions/reactUIDesigner/assets/66732863/00339cb5-c7cb-4467-a38f-b7e926f5279d)

![image](https://github.com/sibvisions/reactUIDesigner/assets/66732863/a05584fd-8460-46f3-b7e7-c300352d7351)

**Comment by rjahn** [comment]
Sure, it can't work with current VisionX, but will with a newer version.
